# Generated by Django 5.2.6 on 2025-09-19 10:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('tractor', 'Tractor'), ('trailer', 'Trailer')], max_length=10)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_number', models.CharField(max_length=20, unique=True)),
                ('initials', models.CharField(max_length=5)),
                ('signature', models.TextField(blank=True, help_text='Digital signature or signature image path')),
                ('home_operating_center', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50)),
                ('license_state', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ELDLogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_off_duty_time', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Line 1 total hours', max_digits=4)),
                ('total_sleeper_berth_time', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Line 2 total hours', max_digits=4)),
                ('total_driving_time', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Line 3 total hours', max_digits=4)),
                ('total_on_duty_time', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Line 4 total hours', max_digits=4)),
                ('total_duty_time', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Driving + On Duty time", max_digits=4)),
                ('miles_driven', models.PositiveIntegerField(default=0)),
                ('hos_violation', models.BooleanField(default=False)),
                ('violation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eld_system.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DutyStatusPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty (Line 1)'), ('sleeper_berth', 'Sleeper Berth (Line 2)'), ('driving', 'Driving (Line 3)'), ('on_duty', 'On Duty Not Driving (Line 4)')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('activity_description', models.CharField(help_text='e.g., pre-trip inspection, fueling, 30-min break', max_length=200)),
                ('vehicle_moved', models.BooleanField(default=True, help_text="False for bracketed periods where truck didn't move")),
                ('grid_start_minute', models.PositiveIntegerField(help_text='Start position in 15-minute increments from midnight (0-1439)')),
                ('grid_end_minute', models.PositiveIntegerField(help_text='End position in 15-minute increments from midnight (0-1439)')),
                ('log_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_periods', to='eld_system.eldlogsheet')),
            ],
            options={
                'ordering': ['log_sheet', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_id', models.CharField(max_length=50, unique=True)),
                ('commodity', models.CharField(help_text='e.g., paper products', max_length=200)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in pounds', null=True)),
                ('pieces', models.PositiveIntegerField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eld_system.shipper')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('current_location', models.CharField(max_length=255)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_cycle_used_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('70'))])),
                ('start_time', models.DateTimeField()),
                ('estimated_end_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('total_estimated_miles', models.PositiveIntegerField(default=0)),
                ('total_actual_miles', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eld_system.driver')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eld_system.load')),
                ('tractor', models.ForeignKey(limit_choices_to={'vehicle_type': 'tractor'}, on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_tractor', to='eld_system.vehicle')),
                ('trailer', models.ForeignKey(blank=True, limit_choices_to={'vehicle_type': 'trailer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_trailer', to='eld_system.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RestBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_type', models.CharField(choices=[('30_min', '30-Minute Break'), ('10_hour', '10-Hour Rest'), ('34_hour', '34-Hour Restart')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_breaks', to='eld_system.trip')),
            ],
            options={
                'ordering': ['trip', 'scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estimated_time', models.DateTimeField()),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('miles_from_start', models.PositiveIntegerField()),
                ('fuel_needed', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops', to='eld_system.trip')),
            ],
            options={
                'ordering': ['trip', 'miles_from_start'],
            },
        ),
        migrations.AddField(
            model_name='eldlogsheet',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='eld_system.trip'),
        ),
        migrations.CreateModel(
            name='HOSCycleTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start_date', models.DateField()),
                ('cycle_end_date', models.DateField()),
                ('total_cycle_hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('70'))])),
                ('remaining_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_violation', models.BooleanField(default=False)),
                ('violation_type', models.CharField(blank=True, max_length=50)),
                ('violation_details', models.TextField(blank=True)),
                ('restart_available', models.BooleanField(default=False)),
                ('restart_start_time', models.DateTimeField(blank=True, null=True)),
                ('restart_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eld_system.driver')),
            ],
            options={
                'unique_together': {('driver', 'cycle_start_date')},
            },
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('waypoint_type', models.CharField(choices=[('route', 'Route Point'), ('fuel', 'Fuel Stop'), ('rest', 'Rest Area'), ('checkpoint', 'Checkpoint')], default='route', max_length=20)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='eld_system.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence'],
                'unique_together': {('trip', 'sequence')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='eldlogsheet',
            unique_together={('driver', 'date')},
        ),
    ]
