# Generated by Django 5.2.6 on 2025-09-27 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='tractor',
        ),
        migrations.AddField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(limit_choices_to={'vehicle_type': 'truck'}, on_delete=django.db.models.deletion.CASCADE, related_name='trips_as_truck', to='eld_system.vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('truck', 'Tractor'), ('trailer', 'Trailer')], max_length=10),
        ),
    ]
