# Generated by Django 5.2.6 on 2025-09-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_system', '0002_remove_trip_tractor_trip_truck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('truck', 'Truck'), ('trailer', 'Trailer')], max_length=10),
        ),
    ]
