# Generated by Django 5.2.6 on 2025-09-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld_system', '0003_alter_trip_start_time_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutystatusperiod',
            name='end_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dutystatusperiod',
            name='end_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dutystatusperiod',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dutystatusperiod',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
